---
version: "3.7"

services:
  local-db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: builder
    volumes:
      - .:/app
    env_file:
      - hitman-api/.env
    command: --py-autoreload=1
    restart: on-failure
    ports:
      - "${PORT:-80}:80"
    depends_on:
      - local-db

  # TODO: enable frontend in docker compose
  #frontend:
  #  build: ./hitman-ui
  #  command: ["npm", "start"]
  #  volumes:
  #    - ./hitman-ui:/app/frontend
  #    - node-modules:/app/frontend/node_modules
  #  ports:
  #    - "3000:3000"

volumes:
  node-modules: