---
version: "3.7"

services:
  local-db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: builder
    image: hitman-api
    volumes:
      - .:/app
    env_file:
      - .env
    command: --py-autoreload=1
    restart: on-failure
    ports:
      - "${PORT:-80}:80"
    depends_on:
      - local-db

  migration:
    image: hitman-api
    entrypoint: /usr/local/bin/python
    command: ./manage.py migrate --noinput
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - local-db
